/**
 * BACF - Battery of Assessment of Cognitive Functioning
 * 
 * This program represents a test for gauging the cognitive reasoning
 * of an individual whom has suffered a traumatic brain injury. There are
 * five separate tests: 25 Numbers, Association, Exclusion, Generalization,
 * and Recall. Each use a timer an point system in order to calculate results,
 * show them to the examiner, and store the information in a database for
 * future management.
 * 
 * Written for Michael Meyerson
 */
package bacf;
import java.awt.Color;

/**
 * This class represents the fourth Exclusion Test page. 
 *
 * @author Brandon Salines
 * @author Anthony Eannarino
 * @author Brian Faria
 */
public class ExclusionTest4 extends ExaminerPage {
    public static final int ID = 14;
    int counter;
    
    /**
     * Creates the page.
     * @param c A reference to the Controller Object
     */
    public ExclusionTest4(Controller c) {
        super(c);
        initComponents();
        counter = 1;
        panelExclusion4.setBackground(DEFAULT);
        this.setPreviousPage(ExclusionTest3.ID);
        this.setNextPage(ExclusionTest5.ID);
        this.setTest(panelExclusion4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelExclusion4 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        spacer = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        excTestBtn4a = new javax.swing.JButton();
        excTestBtn4b = new javax.swing.JButton();
        excTestBtn4d = new javax.swing.JButton();
        excTestBtn4c = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        reasonlbl = new javax.swing.JLabel();
        reasonText = new javax.swing.JLabel();

        panelExclusion4.setBackground(Color.LIGHT_GRAY);
        panelExclusion4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTitle.setText("Exclusion Test");
        panelExclusion4.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 25, 160, 34));
        panelExclusion4.add(spacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 30, 20));
        panelExclusion4.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 320, 30));

        excTestBtn4a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic4a.png"))); // NOI18N
        excTestBtn4a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn4aActionPerformed(evt);
            }
        });
        panelExclusion4.add(excTestBtn4a, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 140, 200, 193));

        excTestBtn4b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic4b.png"))); // NOI18N
        excTestBtn4b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn4bActionPerformed(evt);
            }
        });
        panelExclusion4.add(excTestBtn4b, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 200, 193));

        excTestBtn4d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic4d.png"))); // NOI18N
        excTestBtn4d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn4dActionPerformed(evt);
            }
        });
        panelExclusion4.add(excTestBtn4d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 200, 193));

        excTestBtn4c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic4c.png"))); // NOI18N
        excTestBtn4c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn4cActionPerformed(evt);
            }
        });
        panelExclusion4.add(excTestBtn4c, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 350, 200, 193));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panelExclusion4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 410, 40));

        reasonlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reasonlbl.setText("Reasoning:");
        panelExclusion4.add(reasonlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 564, 110, 30));

        reasonText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reasonText.setForeground(new java.awt.Color(204, 0, 0));
        panelExclusion4.add(reasonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 320, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExclusion4, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelExclusion4, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void excTestBtn4aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn4aActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn4aActionPerformed

    private void excTestBtn4bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn4bActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn4bActionPerformed

    private void excTestBtn4cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn4cActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn4cActionPerformed

    private void excTestBtn4dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn4dActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn4dActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton excTestBtn4a;
    private javax.swing.JButton excTestBtn4b;
    private javax.swing.JButton excTestBtn4c;
    private javax.swing.JButton excTestBtn4d;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelExclusion4;
    private javax.swing.JLabel reasonText;
    private javax.swing.JLabel reasonlbl;
    private javax.swing.JLabel spacer;
    // End of variables declaration//GEN-END:variables
}
