/**
 * BACF - Battery of Assessment of Cognitive Functioning
 * 
 * This program represents a test for gauging the cognitive reasoning
 * of an individual whom has suffered a traumatic brain injury. There are
 * five separate tests: 25 Numbers, Association, Exclusion, Generalization,
 * and Recall. Each use a timer an point system in order to calculate results,
 * show them to the examiner, and store the information in a database for
 * future management.
 * 
 * Written for Michael Meyerson
 */
package bacf;
import java.awt.Color;

/**
 * This class represents the second Exclusion Test page.
 *
 * @author Brandon Salines
 * @author Anthony Eannarino
 * @author Brian Faria
 */
public class ExclusionTest2 extends ExaminerPage {
    public static final int ID = 12;
    int counter;
    
    /**
     * Creates the page.
     * @param c A reference to the Controller Object
     */
    public ExclusionTest2(Controller c) {
        super(c);
        initComponents();
        counter = 1;
        panelExclusion2.setBackground(DEFAULT);
        this.setPreviousPage(ExclusionTest1.ID);
        this.setNextPage(ExclusionTest3.ID);
        this.setTest(panelExclusion2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelExclusion2 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        spacer = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        excTestBtn2a = new javax.swing.JButton();
        excTestBtn2b = new javax.swing.JButton();
        excTestBtn2d = new javax.swing.JButton();
        excTestBtn2c = new javax.swing.JButton();
        reasonText = new javax.swing.JTextField();
        reasonlbl = new javax.swing.JLabel();
        errorLabel1 = new javax.swing.JLabel();

        panelExclusion2.setBackground(Color.LIGHT_GRAY);
        panelExclusion2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTitle.setText("Exclusion Test");
        panelExclusion2.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 25, 160, 34));
        panelExclusion2.add(spacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 30, 20));
        panelExclusion2.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 320, 30));

        excTestBtn2a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic2a.png"))); // NOI18N
        excTestBtn2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn2aActionPerformed(evt);
            }
        });
        panelExclusion2.add(excTestBtn2a, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 140, 200, 193));

        excTestBtn2b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic2b.png"))); // NOI18N
        excTestBtn2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn2bActionPerformed(evt);
            }
        });
        panelExclusion2.add(excTestBtn2b, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 200, 193));

        excTestBtn2d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic2d.png"))); // NOI18N
        excTestBtn2d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn2dActionPerformed(evt);
            }
        });
        panelExclusion2.add(excTestBtn2d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 200, 193));

        excTestBtn2c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic2c.png"))); // NOI18N
        excTestBtn2c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn2cActionPerformed(evt);
            }
        });
        panelExclusion2.add(excTestBtn2c, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 350, 200, 193));

        reasonText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasonTextActionPerformed(evt);
            }
        });
        panelExclusion2.add(reasonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 410, 40));

        reasonlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reasonlbl.setText("Reasoning:");
        panelExclusion2.add(reasonlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 564, 110, 30));

        errorLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        errorLabel1.setForeground(new java.awt.Color(204, 0, 0));
        panelExclusion2.add(errorLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 320, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExclusion2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelExclusion2, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reasonTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasonTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reasonTextActionPerformed

    private void excTestBtn2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn2aActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn2aActionPerformed

    private void excTestBtn2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn2bActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn2bActionPerformed

    private void excTestBtn2cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn2cActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn2cActionPerformed

    private void excTestBtn2dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn2dActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn2dActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel errorLabel1;
    private javax.swing.JButton excTestBtn2a;
    private javax.swing.JButton excTestBtn2b;
    private javax.swing.JButton excTestBtn2c;
    private javax.swing.JButton excTestBtn2d;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelExclusion2;
    private javax.swing.JTextField reasonText;
    private javax.swing.JLabel reasonlbl;
    private javax.swing.JLabel spacer;
    // End of variables declaration//GEN-END:variables
}
