/**
 * BACF - Battery of Assessment of Cognitive Functioning
 * 
 * This program represents a test for gauging the cognitive reasoning
 * of an individual whom has suffered a traumatic brain injury. There are
 * five separate tests: 25 Numbers, Association, Exclusion, Generalization,
 * and Recall. Each use a timer an point system in order to calculate results,
 * show them to the examiner, and store the information in a database for
 * future management.
 * 
 * Written for Michael Meyerson
 */
package bacf;
import java.awt.Color;

/**
 * This class represents the third Exclusion Test page.
 *
 * @author Brandon Salines
 * @author Anthony Eannarino
 * @author Brian Faria
 */
public class ExclusionTest3 extends ExaminerPage {
    public static final int ID = 13;
    int counter;
    
    /**
     * Creates the page.
     * @param c A reference to the Controller Object
     */
    public ExclusionTest3(Controller c) {
        super(c);
        initComponents();
        counter = 1;
        panelExclusion3.setBackground(DEFAULT);
        this.setPreviousPage(ExclusionTest2.ID);
        this.setNextPage(ExclusionTest4.ID);
        this.setTest(panelExclusion3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelExclusion3 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        spacer = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        excTestBtn3a = new javax.swing.JButton();
        excTestBtn3b = new javax.swing.JButton();
        excTestBtn3d = new javax.swing.JButton();
        excTestBtn3c = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        reasonlbl = new javax.swing.JLabel();
        reasonText = new javax.swing.JLabel();

        panelExclusion3.setBackground(Color.LIGHT_GRAY);
        panelExclusion3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTitle.setText("Exclusion Test");
        panelExclusion3.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 25, 160, 34));
        panelExclusion3.add(spacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 30, 20));
        panelExclusion3.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 320, 30));

        excTestBtn3a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic3a.png"))); // NOI18N
        excTestBtn3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn3aActionPerformed(evt);
            }
        });
        panelExclusion3.add(excTestBtn3a, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 140, 200, 193));

        excTestBtn3b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic3b.png"))); // NOI18N
        excTestBtn3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn3bActionPerformed(evt);
            }
        });
        panelExclusion3.add(excTestBtn3b, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 200, 193));

        excTestBtn3d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic3d.png"))); // NOI18N
        excTestBtn3d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn3dActionPerformed(evt);
            }
        });
        panelExclusion3.add(excTestBtn3d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 200, 193));

        excTestBtn3c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic3c.png"))); // NOI18N
        excTestBtn3c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn3cActionPerformed(evt);
            }
        });
        panelExclusion3.add(excTestBtn3c, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 350, 200, 193));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panelExclusion3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 410, 40));

        reasonlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reasonlbl.setText("Reasoning:");
        panelExclusion3.add(reasonlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 564, 110, 30));

        reasonText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reasonText.setForeground(new java.awt.Color(204, 0, 0));
        panelExclusion3.add(reasonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 320, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExclusion3, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelExclusion3, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void excTestBtn3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn3aActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn3aActionPerformed

    private void excTestBtn3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn3bActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn3bActionPerformed

    private void excTestBtn3cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn3cActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn3cActionPerformed

    private void excTestBtn3dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn3dActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn3dActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton excTestBtn3a;
    private javax.swing.JButton excTestBtn3b;
    private javax.swing.JButton excTestBtn3c;
    private javax.swing.JButton excTestBtn3d;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelExclusion3;
    private javax.swing.JLabel reasonText;
    private javax.swing.JLabel reasonlbl;
    private javax.swing.JLabel spacer;
    // End of variables declaration//GEN-END:variables
}
