/**
 * BACF - Battery of Assessment of Cognitive Functioning
 * 
 * This program represents a test for gauging the cognitive reasoning
 * of an individual whom has suffered a traumatic brain injury. There are
 * five separate tests: 25 Numbers, Association, Exclusion, Generalization,
 * and Recall. Each use a timer an point system in order to calculate results,
 * show them to the examiner, and store the information in a database for
 * future management.
 * 
 * Written for Michael Meyerson
 */
package bacf;
import java.awt.Color;

/**
 * This class represents the fifth Exclusion Test page.
 *
 * @author Brandon Salines
 * @author Anthony Eannarino
 * @author Brian Faria
 */
public class ExclusionTest5 extends ExaminerPage {
    public static final int ID = 15;
    int counter;
    
    /**
     * Creates the page.
     * @param c A reference to the Controller Object
     */
    public ExclusionTest5(Controller c) {
        super(c);
        initComponents();
        counter = 1;
        panelExclusion5.setBackground(DEFAULT);
        this.setPreviousPage(ExclusionTest4.ID);
        this.setNextPage(GeneralizationTest1.ID);
        this.setTest(panelExclusion5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelExclusion5 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        spacer = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        excTestBtn5a = new javax.swing.JButton();
        excTestBtn5b = new javax.swing.JButton();
        excTestBtn5d = new javax.swing.JButton();
        excTestBtn5c = new javax.swing.JButton();
        reasonlbl = new javax.swing.JLabel();
        reasonText = new javax.swing.JTextField();
        errorLabel1 = new javax.swing.JLabel();

        panelExclusion5.setBackground(Color.LIGHT_GRAY);
        panelExclusion5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTitle.setText("Exclusion Test");
        panelExclusion5.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 25, 160, 34));
        panelExclusion5.add(spacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 30, 20));
        panelExclusion5.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 320, 30));

        excTestBtn5a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic5a.png"))); // NOI18N
        excTestBtn5a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn5aActionPerformed(evt);
            }
        });
        panelExclusion5.add(excTestBtn5a, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 140, 200, 193));

        excTestBtn5b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic5b.png"))); // NOI18N
        excTestBtn5b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn5bActionPerformed(evt);
            }
        });
        panelExclusion5.add(excTestBtn5b, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 200, 193));

        excTestBtn5d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic5d.png"))); // NOI18N
        excTestBtn5d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn5dActionPerformed(evt);
            }
        });
        panelExclusion5.add(excTestBtn5d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 200, 193));

        excTestBtn5c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic5c.png"))); // NOI18N
        excTestBtn5c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn5cActionPerformed(evt);
            }
        });
        panelExclusion5.add(excTestBtn5c, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 350, 200, 193));

        reasonlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reasonlbl.setText("Reasoning:");
        panelExclusion5.add(reasonlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 564, 110, 30));

        reasonText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasonTextActionPerformed(evt);
            }
        });
        panelExclusion5.add(reasonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 410, 40));

        errorLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        errorLabel1.setForeground(new java.awt.Color(204, 0, 0));
        panelExclusion5.add(errorLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 320, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExclusion5, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelExclusion5, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reasonTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasonTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reasonTextActionPerformed

    private void excTestBtn5aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn5aActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn5aActionPerformed

    private void excTestBtn5bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn5bActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn5bActionPerformed

    private void excTestBtn5cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn5cActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn5cActionPerformed

    private void excTestBtn5dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn5dActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn5dActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel errorLabel1;
    private javax.swing.JButton excTestBtn5a;
    private javax.swing.JButton excTestBtn5b;
    private javax.swing.JButton excTestBtn5c;
    private javax.swing.JButton excTestBtn5d;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelExclusion5;
    private javax.swing.JTextField reasonText;
    private javax.swing.JLabel reasonlbl;
    private javax.swing.JLabel spacer;
    // End of variables declaration//GEN-END:variables
}
