/**
 * BACF - Battery of Assessment of Cognitive Functioning
 * 
 * This program represents a test for gauging the cognitive reasoning
 * of an individual whom has suffered a traumatic brain injury. There are
 * five separate tests: 25 Numbers, Association, Exclusion, Generalization,
 * and Recall. Each use a timer an point system in order to calculate results,
 * show them to the examiner, and store the information in a database for
 * future management.
 * 
 * Written for Michael Meyerson
 */
package bacf;
import java.awt.Color;

/**
 * This class represents the first Exclusion Test page.
 *
 * @author aeann
 */
public class ExclusionTest1 extends ExaminerPage {
    public static final int ID = 11;
    int counter;
    
    
    /**
     * Creates the page.
     * @param c A reference to the Controller Object
     */
    public ExclusionTest1(Controller c) {
        super(c);
        initComponents();
        counter = 1;
        reasonlbl.setVisible(false);
        reasonText.setVisible(false);
        panelExclusion1.setBackground(DEFAULT);
        this.setPreviousPage(AssociationTest.ID);
        this.setNextPage(ExclusionTest2.ID);
        this.setTest(panelExclusion1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelExclusion1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        spacer = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        excTestBtn1a = new javax.swing.JButton();
        excTestBtn1b = new javax.swing.JButton();
        excTestBtn1d = new javax.swing.JButton();
        excTestBtn1c = new javax.swing.JButton();
        reasonText = new javax.swing.JTextField();
        reasonlbl = new javax.swing.JLabel();

        panelExclusion1.setBackground(Color.LIGHT_GRAY);
        panelExclusion1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelTitle.setText("Exclusion Test");
        panelExclusion1.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 25, 160, 34));
        panelExclusion1.add(spacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 30, 20));

        errorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(204, 0, 0));
        panelExclusion1.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 320, 30));

        excTestBtn1a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic1a.png"))); // NOI18N
        excTestBtn1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn1aActionPerformed(evt);
            }
        });
        panelExclusion1.add(excTestBtn1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 140, 200, 193));

        excTestBtn1b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic1b.png"))); // NOI18N
        excTestBtn1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn1bActionPerformed(evt);
            }
        });
        panelExclusion1.add(excTestBtn1b, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 200, 193));

        excTestBtn1d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic1d.png"))); // NOI18N
        excTestBtn1d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn1dActionPerformed(evt);
            }
        });
        panelExclusion1.add(excTestBtn1d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 200, 193));

        excTestBtn1c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bacf/pictures/exclTestPic1c.png"))); // NOI18N
        excTestBtn1c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTestBtn1cActionPerformed(evt);
            }
        });
        panelExclusion1.add(excTestBtn1c, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 350, 200, 193));

        reasonText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasonTextActionPerformed(evt);
            }
        });
        panelExclusion1.add(reasonText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 410, 40));

        reasonlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reasonlbl.setText("Reasoning:");
        panelExclusion1.add(reasonlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 564, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelExclusion1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelExclusion1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void excTestBtn1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn1aActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn1aActionPerformed

    private void reasonTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasonTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reasonTextActionPerformed

    private void excTestBtn1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn1bActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn1bActionPerformed

    private void excTestBtn1cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn1cActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn1cActionPerformed

    private void excTestBtn1dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTestBtn1dActionPerformed
        // TODO add your handling code here:
        if(testStarted == true){
        errorLabel.setText("");
        myTimer.stop();
        reasonlbl.setVisible(true);
        reasonText.setVisible(true);
        }
        else{
            errorLabel.setText("Press Start to begin the test.");
        }
    }//GEN-LAST:event_excTestBtn1dActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton excTestBtn1a;
    private javax.swing.JButton excTestBtn1b;
    private javax.swing.JButton excTestBtn1c;
    private javax.swing.JButton excTestBtn1d;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelExclusion1;
    private javax.swing.JTextField reasonText;
    private javax.swing.JLabel reasonlbl;
    private javax.swing.JLabel spacer;
    // End of variables declaration//GEN-END:variables
}
