/**
 * BACF - Battery of Assessment of Cognitive Functioning
 * 
 * This program represents a test for gauging the cognitive reasoning
 * of an individual whom has suffered a traumatic brain injury. There are
 * five separate tests: 25 Numbers, Association, Exclusion, Generalization,
 * and Recall. Each use a timer an point system in order to calculate results,
 * show them to the examiner, and store the information in a database for
 * future management.
 * 
 * Written for Michael Meyerson
 */
package bacf;

/**
 * This class represents the starting page of the program.
 *
 * @author Brandon Salines
 * @author Anthony Eannarino
 * @author Brian Faria
 */
public class NeworPrevPatient extends ExaminerPage {
    public static final int ID = 1;
   
    
    /**
     * Creates the page.
     * @param c A reference to the Controller Object
     */
    public NeworPrevPatient(Controller c) {
        super(c);
        //super.setBackground(DEFAULT);
        initComponents();
        this.setEnabledButtons(false);
        panelMain.setBackground(DEFAULT);
        this.setTest(panelMain);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        labelBACF = new javax.swing.JLabel();
        LabelBACFTitle = new javax.swing.JLabel();
        buttonPreviousPatient = new javax.swing.JButton();
        buttonNewPatient = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setMinimumSize(new java.awt.Dimension(670, 276));
        setPreferredSize(new java.awt.Dimension(670, 276));

        labelBACF.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        labelBACF.setText("Battery of Assessment of Cognitive Functioning");

        LabelBACFTitle.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        LabelBACFTitle.setText("BACF");

        buttonPreviousPatient.setText("Previous Patient");
        buttonPreviousPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPreviousPatientActionPerformed(evt);
            }
        });

        buttonNewPatient.setText("New Patient");
        buttonNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(labelBACF)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonNewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonPreviousPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(LabelBACFTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(LabelBACFTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBACF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPreviousPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Shows the NewPatient page.
     * @param evt 
     */
    private void buttonNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewPatientActionPerformed
        // TODO add your handling code here:
        this.getController().showPage(NewPatient.ID);
    }//GEN-LAST:event_buttonNewPatientActionPerformed

    /**
     * Shows the PrevPatient page. Loads the table in the PrevPatient page first.
     * @param evt 
     */
    private void buttonPreviousPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPreviousPatientActionPerformed
        // TODO add your handling code here:
        ((PrevPatient) this.getController().getPage(PrevPatient.ID)).populateTable();
        this.getController().showPage(PrevPatient.ID);
    }//GEN-LAST:event_buttonPreviousPatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBACFTitle;
    private javax.swing.JButton buttonNewPatient;
    private javax.swing.JButton buttonPreviousPatient;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelBACF;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}