/**
 * BACF - Battery of Assessment of Cognitive Functioning
 * 
 * This program represents a test for gauging the cognitive reasoning
 * of an individual whom has suffered a traumatic brain injury. There are
 * five separate tests: 25 Numbers, Association, Exclusion, Generalization,
 * and Recall. Each use a timer an point system in order to calculate results,
 * show them to the examiner, and store the information in a database for
 * future management.
 * 
 * Written for Michael Meyerson
 */
package bacf;
import java.awt.Color;
/**
 * This page represents the conclusions for the 25 Numbers Test
 * and the Association Test.
 *
 * @author Brandon Salines
 * @author Anthony Eannarino
 * @author Brian Faria
 */
public class ResultsPage5 extends ExaminerPage {
    public static final int ID = 30;
    
    /**
     * Creates the page
     * @param c A reference to the Controller Object
     */
    public ResultsPage5(Controller c) {
        super(c);
        super.setBackground(DEFAULT);
        initComponents();
        panelResults5.setBackground(DEFAULT);
        this.setPreviousPage(ResultsPage4.ID);
        this.setNextPage(ResultsPage6.ID);
        this.setTest(panelResults5);
        this.setEnabledStart(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelResults5 = new javax.swing.JPanel();
        AssocTestTotalPoints4 = new javax.swing.JLabel();
        AssocTestTotalSeconds2 = new javax.swing.JLabel();
        AssocTestTotalPoints5 = new javax.swing.JLabel();
        AssocTestseconds1 = new javax.swing.JLabel();
        AssocTestPoints2 = new javax.swing.JLabel();
        AssocTestPoints3 = new javax.swing.JLabel();
        numTestTotalPoints3 = new javax.swing.JLabel();
        numTestTotalSeconds1 = new javax.swing.JLabel();
        numTestTotalPoints2 = new javax.swing.JLabel();
        numTestseconds = new javax.swing.JLabel();
        numTestPoints = new javax.swing.JLabel();
        numTestPoints1 = new javax.swing.JLabel();
        labelNumbersTest = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaNumbersTest = new javax.swing.JTextArea();
        labelAssociationTest = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaAssociation = new javax.swing.JTextArea();

        panelResults5.setBackground(Color.LIGHT_GRAY);
        panelResults5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelResults5.add(AssocTestTotalPoints4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 50, 20));
        panelResults5.add(AssocTestTotalSeconds2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 50, 20));
        panelResults5.add(AssocTestTotalPoints5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 50, 20));
        panelResults5.add(AssocTestseconds1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 50, 20));
        panelResults5.add(AssocTestPoints2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 50, 20));
        panelResults5.add(AssocTestPoints3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 50, 20));
        panelResults5.add(numTestTotalPoints3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 273, 50, 20));
        panelResults5.add(numTestTotalSeconds1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 50, 20));
        panelResults5.add(numTestTotalPoints2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 50, 20));
        panelResults5.add(numTestseconds, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 50, 20));
        panelResults5.add(numTestPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 80, 50, 20));
        panelResults5.add(numTestPoints1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 50, 20));

        labelNumbersTest.setText(" Conclusion for the \"25 Numbers Test\"");
        panelResults5.add(labelNumbersTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jScrollPane1.setBorder(null);

        textAreaNumbersTest.setEditable(false);
        textAreaNumbersTest.setBackground(new java.awt.Color(240, 240, 240));
        textAreaNumbersTest.setColumns(20);
        textAreaNumbersTest.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textAreaNumbersTest.setRows(5);
        textAreaNumbersTest.setText("\n  The Alpha-Reactogram of the '25 Numbers Test' represents stability of dynamics of examinee's tempo of sensorimotor \n\n  reaction time. The configuration of the diagram from the first to fifth table trial of the 25 numbers test is:                  point(s)\n\n  Dynamics of searching time is:                        second(s)\n\n              The 25 Numbers Test represents an optimal total index of examinee's tempo of sensorimotor reaction time.\n\n  The total index of examinee's tempo of sensorimotor reactions time after five table trials is:                point(s).\n\n  Total time is              second(s)\n\n             The attentiongram of the 25 numbers test represents stability of examinee's dynamics of productivity of attention.\n\n  The configuration of the diagram from the first to fifth table of the 25 numbers test is                    point(s).\n\n  Total index of examinee's level of productivity of attention after 5 tables of the 25 numbers test is         point(s).\n\n");
        textAreaNumbersTest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(textAreaNumbersTest);

        panelResults5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 610, 290));

        labelAssociationTest.setText(" Conclusion for the \"Association Test\"");
        panelResults5.add(labelAssociationTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 20));

        jScrollPane2.setBorder(null);

        textAreaAssociation.setEditable(false);
        textAreaAssociation.setBackground(new java.awt.Color(240, 240, 240));
        textAreaAssociation.setColumns(20);
        textAreaAssociation.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textAreaAssociation.setRows(5);
        textAreaAssociation.setText("\n  The Beta-Reactogram of the 'Associations Test' represents inertness of dynamics of examinee's tempo of recalling \n\n  reaction time. The configuration of the diagram from the first to fifth trial of theAssociations test is:               point(s)\n\n  Dynamics of recalling time is:              second(s)\n\n              The Associations Test represents an optimal total index of examinee's tempo of recalling reaction time.\n\n  The total index of examinee's tempo of recalling reactions time after five picture trials is:                point(s).\n\n  Total time is              second(s)\n\n             The memogram of the Associations test represents inertness of examinee's dynamics of productivity of memory.\n\n  The configuration of the diagram from the first to fifth trial of the Associations test is                    point(s).\n\n  Total index of examinee's level of productivity of memory after 5 tables of the Associations test is              point(s).\n\n");
        textAreaAssociation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(textAreaAssociation);

        panelResults5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 610, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelResults5, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelResults5, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AssocTestPoints2;
    private javax.swing.JLabel AssocTestPoints3;
    private javax.swing.JLabel AssocTestTotalPoints4;
    private javax.swing.JLabel AssocTestTotalPoints5;
    private javax.swing.JLabel AssocTestTotalSeconds2;
    private javax.swing.JLabel AssocTestseconds1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAssociationTest;
    private javax.swing.JLabel labelNumbersTest;
    private javax.swing.JLabel numTestPoints;
    private javax.swing.JLabel numTestPoints1;
    private javax.swing.JLabel numTestTotalPoints2;
    private javax.swing.JLabel numTestTotalPoints3;
    private javax.swing.JLabel numTestTotalSeconds1;
    private javax.swing.JLabel numTestseconds;
    private javax.swing.JPanel panelResults5;
    private javax.swing.JTextArea textAreaAssociation;
    private javax.swing.JTextArea textAreaNumbersTest;
    // End of variables declaration//GEN-END:variables
}
