/**
 * BACF - Battery of Assessment of Cognitive Functioning
 * 
 * This program represents a test for gauging the cognitive reasoning
 * of an individual whom has suffered a traumatic brain injury. There are
 * five separate tests: 25 Numbers, Association, Exclusion, Generalization,
 * and Recall. Each use a timer an point system in order to calculate results,
 * show them to the examiner, and store the information in a database for
 * future management.
 * 
 * Written for Michael Meyerson
 */
package bacf;
import java.awt.Color;
/**
 * This class represents the final Results page displaying
 * the final conclusions and allows for additional comments.
 *
 * @author Brandon Salines
 * @author Anthony Eannarino
 * @author Brian Faria
 */
public class ResultsPage7 extends ExaminerPage {
    public static final int ID = 32;
    
    /**
     * Creates the page
     * @param c A reference to the Controller Object
     */
    public ResultsPage7(Controller c) {
        super(c);
        super.setBackground(DEFAULT);
        initComponents();
        panelResultsl7.setBackground(DEFAULT);
        this.setPreviousPage(ResultsPage6.ID);
        this.setNextPage(NeworPrevPatient.ID);
        this.setTest(panelResultsl7);    // Loads panel with side buttons
        this.setEnabledStart(false);   // Disables start button
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelResultsl7 = new javax.swing.JPanel();
        GeneralPoints = new javax.swing.JLabel();
        GeneralTotalPoints = new javax.swing.JLabel();
        GeneralTotalSeconds = new javax.swing.JLabel();
        GeneralSeconds = new javax.swing.JLabel();
        labelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaComments = new javax.swing.JTextArea();
        labelComments = new javax.swing.JLabel();

        panelResultsl7.setBackground(Color.LIGHT_GRAY);
        panelResultsl7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelResultsl7.add(GeneralPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 187, 70, 20));
        panelResultsl7.add(GeneralTotalPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 40, 20));
        panelResultsl7.add(GeneralTotalSeconds, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 50, 20));
        panelResultsl7.add(GeneralSeconds, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 90, 20));

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTitle.setText("General Conclusion");
        panelResultsl7.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        jScrollPane1.setBorder(null);

        textArea.setEditable(false);
        textArea.setBackground(new java.awt.Color(240, 240, 240));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textArea.setRows(5);
        textArea.setText("\n  The BACF Profile of the Tempo of Cognitive Functioning represents ordinarily intensive lability of examinee's Tempo of\n\n  cognitive functioning. The configuration of the diagram from 1st to 4th test of BACF is                                 point(s).\n\n  Tempo of cognitive function is                         second(s).\n\n  The Full Index of Examinee's Tempo of Cognitive Functioning after four tests of BACF is               point(s).\n\n  Full time is                  second(s).\n");
        textArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(textArea);

        panelResultsl7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 610, 160));

        textAreaComments.setColumns(20);
        textAreaComments.setRows(5);
        jScrollPane3.setViewportView(textAreaComments);

        panelResultsl7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 610, 150));

        labelComments.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelComments.setText("Comments:");
        panelResultsl7.add(labelComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelResultsl7, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelResultsl7, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GeneralPoints;
    private javax.swing.JLabel GeneralSeconds;
    private javax.swing.JLabel GeneralTotalPoints;
    private javax.swing.JLabel GeneralTotalSeconds;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelComments;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelResultsl7;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextArea textAreaComments;
    // End of variables declaration//GEN-END:variables
}
