/**
 * BACF - Battery of Assessment of Cognitive Functioning
 * 
 * This program represents a test for gauging the cognitive reasoning
 * of an individual whom has suffered a traumatic brain injury. There are
 * five separate tests: 25 Numbers, Association, Exclusion, Generalization,
 * and Recall. Each use a timer an point system in order to calculate results,
 * show them to the examiner, and store the information in a database for
 * future management.
 * 
 * Written for Michael Meyerson
 */
package bacf;
import java.awt.Color;
/**
 * This class represents the sixth Results Page, showing
 * conclusions for the Exclusion and Generalization tests.
 *
 * @author Brandon Salines
 * @author Anthony Eannarino
 * @author Brian Faria
 */
public class ResultsPage6 extends ExaminerPage {
    
    public static final int ID = 31;
    int assocCounter = 0;
    int counter=1;
    
    /**
     * Creates the page.
     * @param c A reference to the Controller Object
     */
    public ResultsPage6(Controller c) {
        super(c);
        super.setBackground(DEFAULT);
        initComponents();
        panelResults6.setBackground(DEFAULT);
        this.setPreviousPage(ResultsPage5.ID);
        this.setNextPage(ResultsPage7.ID);
        this.setTest(panelResults6);
        this.setEnabledStart(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelResults6 = new javax.swing.JPanel();
        ExcTestTotalPoints3 = new javax.swing.JLabel();
        ExcTestTotalSeconds1 = new javax.swing.JLabel();
        ExcTestTotalPoints2 = new javax.swing.JLabel();
        ExcTestseconds = new javax.swing.JLabel();
        ExcTestPoints = new javax.swing.JLabel();
        ExcTestPoints1 = new javax.swing.JLabel();
        GenTestTotalPoints4 = new javax.swing.JLabel();
        GenTestTotalSeconds2 = new javax.swing.JLabel();
        GenTestTotalPoints5 = new javax.swing.JLabel();
        GenTestseconds1 = new javax.swing.JLabel();
        GenTestPoints2 = new javax.swing.JLabel();
        GenTestPoints3 = new javax.swing.JLabel();
        labelExclusion = new javax.swing.JLabel();
        labelGeneralization = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaExclusion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        teaxtAreaGeneralization = new javax.swing.JTextArea();

        panelResults6.setBackground(Color.LIGHT_GRAY);
        panelResults6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelResults6.add(ExcTestTotalPoints3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 273, 50, 20));
        panelResults6.add(ExcTestTotalSeconds1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 50, 20));
        panelResults6.add(ExcTestTotalPoints2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 50, 20));
        panelResults6.add(ExcTestseconds, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 50, 20));
        panelResults6.add(ExcTestPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 50, 20));
        panelResults6.add(ExcTestPoints1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 50, 20));
        panelResults6.add(GenTestTotalPoints4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 50, 20));
        panelResults6.add(GenTestTotalSeconds2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 50, 20));
        panelResults6.add(GenTestTotalPoints5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 50, 20));
        panelResults6.add(GenTestseconds1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 50, 20));
        panelResults6.add(GenTestPoints2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 50, 20));
        panelResults6.add(GenTestPoints3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 50, 20));

        labelExclusion.setText(" Conclusion for the \"Exclusions Test\"");
        panelResults6.add(labelExclusion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        labelGeneralization.setText(" Conclusion for the \"Generalization Test\"");
        panelResults6.add(labelGeneralization, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 20));

        jScrollPane1.setBorder(null);

        textAreaExclusion.setEditable(false);
        textAreaExclusion.setBackground(new java.awt.Color(240, 240, 240));
        textAreaExclusion.setColumns(20);
        textAreaExclusion.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textAreaExclusion.setRows(5);
        textAreaExclusion.setText("\n  The Gamma-Reactogram of the 'Exclusions Test' represents stability of dynamics of examinee's tempo of exclusion \n\n  reaction time. The configuration of the diagram from the first to fifth table trial of the Exclusions test is:               point(s)\n\n  Dynamics of searching time is:              second(s)\n\n              The Exclusions Test represents an optimal total index of examinee's tempo of exclusion reaction time.\n\n  The total index of examinee's tempo of sensorimotor reactions time after five trials is:                point(s).\n\n  Total time is              second(s)\n\n             The Exclusiongram of the Exclusions test represents stability of examinee's dynamics of productivity of attention.\n\n  The configuration of the diagram from the first to fifth table of the Exclusions test is                    point(s).\n\n  Total index of examinee's level of productivity of attention after 5 tables of the Exclusions test is         point(s).\n\n");
        textAreaExclusion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(textAreaExclusion);

        panelResults6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 610, 290));

        jScrollPane2.setBorder(null);

        teaxtAreaGeneralization.setEditable(false);
        teaxtAreaGeneralization.setBackground(new java.awt.Color(240, 240, 240));
        teaxtAreaGeneralization.setColumns(20);
        teaxtAreaGeneralization.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        teaxtAreaGeneralization.setRows(5);
        teaxtAreaGeneralization.setText("\n  The Delta-Reactogram of the 'Generalization Test' represents inertness of dynamics of examinee's tempo of recalling \n\n  reaction time. The configuration of the diagram from the first to fifth trial of the Generalization test is:               point(s)\n\n  Dynamics of recalling time is:              second(s)\n\n              The Generalization Test represents an optimal total index of examinee's tempo of recalling reaction time.\n\n  The total index of examinee's tempo of recalling reactions time after five picture trials is:                point(s).\n\n  Total time is              second(s)\n\n             The memogram of the Generalization test represents inertness of examinee's dynamics of productivity of memory.\n\n  The configuration of the diagram from the first to fifth trial of the Generalization test is                    point(s).\n\n  Total index of examinee's level of productivity of memory after 5 tables of the Generalization test is         point(s).\n\n");
        teaxtAreaGeneralization.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(teaxtAreaGeneralization);

        panelResults6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 610, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelResults6, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelResults6, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExcTestPoints;
    private javax.swing.JLabel ExcTestPoints1;
    private javax.swing.JLabel ExcTestTotalPoints2;
    private javax.swing.JLabel ExcTestTotalPoints3;
    private javax.swing.JLabel ExcTestTotalSeconds1;
    private javax.swing.JLabel ExcTestseconds;
    private javax.swing.JLabel GenTestPoints2;
    private javax.swing.JLabel GenTestPoints3;
    private javax.swing.JLabel GenTestTotalPoints4;
    private javax.swing.JLabel GenTestTotalPoints5;
    private javax.swing.JLabel GenTestTotalSeconds2;
    private javax.swing.JLabel GenTestseconds1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelExclusion;
    private javax.swing.JLabel labelGeneralization;
    private javax.swing.JPanel panelResults6;
    private javax.swing.JTextArea teaxtAreaGeneralization;
    private javax.swing.JTextArea textAreaExclusion;
    // End of variables declaration//GEN-END:variables
}
